package io.github.zebalu.aoc2022;

import java.util.List;

public class Day02 {
    public static void main(String[] args) {
        var games = readGames(INPUT);
        System.out.println(calculateScore(games));
        System.out.println(calculateRightScore(games));
    }

    private static List<Game> readGames(String input) {
        return input.lines().map(l -> new Game(l.split(" "))).toList();
    }

    private static enum RPS {
        ROCK(1), PAPER(2), SCISSORS(3);

        final int value;

        private RPS(int value) {
            this.value = value;
        }
    }

    private static int myPoints(RPS me, RPS him) {
        if (me == him) {
            return 3 + me.value;
        } else {
            if (isBeating(me, him)) {
                return 6 + me.value;
            } else {
                return 0 + me.value;
            }
        }
    }

    private static boolean isBeating(RPS me, RPS him) {
        if (me == RPS.ROCK) {
            if (him == RPS.SCISSORS) {
                return true;
            }
            return false;
        } else if (me == RPS.PAPER) {
            if (him == RPS.ROCK) {
                return true;
            }
            return false;
        } else {
            if (him == RPS.PAPER) {
                return true;
            }
            return false;
        }
    }

    private static final record Game(String him, String me) {
        Game(String[] splited) {
            this(splited[0], splited[1]);
        }

        RPS himRps() {
            return switch (him) {
            case "A" -> RPS.ROCK;
            case "B" -> RPS.PAPER;
            case "C" -> RPS.SCISSORS;
            default -> throw new IllegalArgumentException("What is this? '" + him + "'");
            };
        }

        RPS meBasicRps() {
            return switch (me) {
            case "Y" -> RPS.PAPER;
            case "X" -> RPS.ROCK;
            case "Z" -> RPS.SCISSORS;
            default -> throw new IllegalArgumentException("What is this? '" + me + "'");
            };
        }

        RPS meAdvancedRps() {
            return selectFor(himRps(), me);
        }
    }

    private static int calculateScore(List<Game> games) {
        return games.stream().mapToInt(g -> myPoints(g.meBasicRps(), g.himRps())).sum();
    }

    private static int calculateRightScore(List<Game> games) {
        return games.stream().mapToInt(g -> myPoints(g.meAdvancedRps(), g.himRps())).sum();
    }

    private static RPS selectFor(RPS him, String letter) {
        if (letter.equals("Y")) {
            return him;
        } else if (letter.equals("X")) {
            return switch (him) {
            case PAPER -> RPS.ROCK;
            case ROCK -> RPS.SCISSORS;
            case SCISSORS -> RPS.PAPER;
            };
        } else if (letter.equals("Z")) {
            return switch (him) {
            case PAPER -> RPS.SCISSORS;
            case ROCK -> RPS.PAPER;
            case SCISSORS -> RPS.ROCK;
            };
        } else {
            throw new IllegalStateException("unknown letter: '" + letter + "'");
        }
    }

    private static final String INPUT = """
            A X
            B Y
            B Y
            C X
            B X
            C Z
            C Z
            A Z
            A Z
            B Y
            C Z
            A Z
            C Z
            C X
            B Z
            C Z
            C Z
            C Z
            B Y
            C Z
            C Z
            C Z
            A Z
            A Y
            B Z
            B Z
            A Y
            B X
            C Z
            C Z
            A Z
            A Z
            C Z
            A Y
            A X
            A Z
            A Z
            B X
            B Z
            B X
            A Z
            B X
            B Z
            B Z
            C Z
            A Z
            A Z
            A Z
            C Z
            B Z
            A Z
            A Y
            A Y
            B Y
            B Y
            B Z
            A Z
            B Z
            A Z
            B Z
            C Z
            B Y
            A Z
            B Y
            A Z
            A Z
            A Z
            C Z
            A Y
            A Z
            C Z
            C Z
            A Z
            A X
            B Y
            C Z
            A Z
            A Z
            C X
            C Z
            B X
            C X
            B X
            A Z
            C Z
            C Z
            A Y
            A Z
            B X
            C X
            A Z
            A Z
            C Z
            C Z
            B Y
            C Z
            A Z
            A Z
            A Y
            B X
            B Y
            A Z
            C Z
            A Z
            A Z
            A Z
            C X
            C Y
            C Z
            B X
            B X
            B X
            A Z
            A X
            C Z
            A Z
            B Y
            B X
            A Y
            B X
            A Z
            C Z
            C Z
            A X
            A Z
            C Z
            B Z
            B X
            A Z
            C Z
            C Z
            C X
            C Z
            C Z
            C Z
            A Y
            B X
            A Y
            A Z
            B Z
            B Z
            C Z
            B Z
            B Z
            B X
            A Z
            C Z
            A Z
            A Y
            C Z
            A Z
            C X
            A Z
            A Z
            A Y
            A Y
            A Z
            C Z
            B Y
            A X
            A Z
            A Y
            C Z
            A Z
            B X
            A Z
            B Y
            A X
            C X
            B X
            A Y
            A Z
            B Z
            A Z
            A Z
            B X
            A X
            C Z
            B X
            B Y
            A Z
            B X
            C Z
            A Z
            C Z
            B X
            A Z
            A Y
            A Z
            A Z
            B X
            B X
            B Z
            A Z
            B Y
            C Z
            B Z
            C Z
            C Z
            B X
            B X
            A Z
            C Z
            C Z
            A X
            B X
            B X
            A Y
            C Z
            A Z
            A Y
            B X
            A Z
            A Z
            B X
            A Z
            C Z
            B X
            B Z
            B Y
            B X
            A Y
            C Z
            C Z
            C Z
            A X
            C Z
            A Z
            C Z
            C Y
            C Z
            C Z
            C Z
            B X
            A Z
            B X
            B Z
            A Z
            C Z
            B Y
            B Y
            B Z
            C Z
            C Z
            C Z
            B Z
            B Y
            A Z
            B X
            B Z
            C Z
            A Z
            B Y
            B Y
            A X
            C Z
            B Y
            A Y
            B Y
            B X
            B Y
            B Y
            A Y
            B Y
            C X
            A Y
            A Y
            C Z
            A Z
            A Y
            C Z
            A Z
            A Z
            C Z
            C Z
            C Z
            B X
            B Y
            A Y
            A Y
            B Z
            A Z
            B Y
            B X
            B Y
            A Y
            A Y
            A Z
            B Z
            C Z
            C Z
            C Z
            A Z
            C Z
            A Z
            A Z
            A Z
            A Z
            C Z
            B Y
            C Z
            B X
            C Z
            A X
            A Z
            B X
            C Y
            C X
            A X
            A X
            A Z
            A Z
            B X
            A Y
            B Z
            A Z
            B Z
            A Z
            C Z
            C X
            C Z
            C Z
            C X
            C Z
            C Z
            C X
            C Z
            B Z
            A Z
            B Y
            A Z
            C Z
            B X
            C Z
            B Z
            B Y
            A Z
            B Y
            A Y
            B X
            B Z
            B Z
            A Z
            B Z
            C Z
            C Z
            A Y
            A Z
            A X
            A Y
            C Z
            B X
            A Z
            C X
            A Z
            A Z
            A Z
            A Z
            C Y
            B Y
            B Y
            A X
            C Z
            A X
            A Z
            A Y
            C X
            A Y
            A Y
            A Z
            C X
            C Z
            B Z
            B X
            A Z
            C Z
            C Z
            B Z
            B X
            C Z
            C Z
            A Y
            B Z
            A X
            B Y
            A Z
            C X
            B X
            C Z
            B Y
            A X
            A Z
            B Y
            A Y
            A Z
            B Z
            A Y
            B Y
            A Z
            B Y
            B X
            B Z
            A Z
            B Y
            B Z
            A Y
            A Z
            C Z
            B X
            C Z
            B X
            C Z
            B Z
            C Z
            C Z
            B Z
            A Y
            A Y
            C Z
            B Z
            A Z
            A X
            C Z
            A Z
            C Z
            A Z
            A X
            A Z
            A Z
            A Y
            B Z
            B X
            C X
            B Y
            C Z
            B X
            B Z
            B X
            A Z
            A Z
            A Z
            B Z
            B Y
            A Z
            B Y
            C Z
            B Z
            A Z
            A Y
            C Z
            A Z
            B Y
            B X
            B Y
            B X
            C Z
            C Y
            A Z
            C Z
            C Z
            A Z
            C X
            B Z
            A Y
            B Y
            B Y
            B Y
            C Z
            B Z
            A Z
            B Y
            A Z
            A Z
            C Z
            B Y
            B Y
            A X
            A Z
            A Z
            C Z
            A Z
            C Z
            C Z
            A X
            B Z
            A Z
            A Z
            C Z
            C Z
            B Y
            B Y
            A Z
            A Y
            A Z
            B Y
            B Z
            A Y
            B Z
            A Z
            A Z
            A Y
            C Z
            A Y
            C Z
            B X
            A Z
            A Z
            C Z
            A Y
            C Z
            A Z
            A Y
            A Y
            C Z
            A Z
            A Y
            B X
            A Y
            B X
            A Z
            A Z
            A Y
            B Y
            B Y
            B X
            C Z
            C Z
            B Y
            B X
            C Z
            B Y
            C Z
            B Y
            B X
            C Z
            A Y
            B Z
            C X
            A Y
            C Z
            C Z
            C X
            A Y
            A Z
            B X
            C Z
            A Z
            B Y
            C Z
            B X
            B Z
            C Z
            C Z
            C Z
            A Z
            B X
            C Z
            A Z
            A Y
            B Y
            C Z
            A X
            C Z
            A Y
            C X
            A Y
            B Y
            C Z
            B X
            A Z
            C Z
            C Z
            B Z
            B Y
            A Z
            A Z
            A Y
            C Z
            A Y
            A X
            A Y
            B Z
            C Z
            C Z
            A Z
            A Z
            C Z
            A Y
            C Z
            C Z
            B Z
            C Z
            C Z
            A Z
            C Z
            B Z
            C Z
            B X
            A Y
            A Y
            A Z
            C X
            C Z
            C Y
            C Z
            C Z
            C Z
            B Z
            A Z
            C Z
            C Z
            A Y
            B Y
            B X
            B X
            C Z
            A Z
            B Y
            C Z
            C Z
            B X
            C Z
            C Z
            A Y
            A Y
            A Z
            A Y
            B Y
            C Z
            A X
            A Y
            C Z
            A Z
            C Z
            C Z
            A X
            A Z
            C Z
            B Z
            A Z
            A Z
            B Y
            B X
            A Z
            A Z
            B Z
            C Z
            C Z
            A Y
            A Z
            B Z
            B Z
            C Z
            B Z
            A Y
            B X
            A Z
            B X
            C Z
            A Z
            A Y
            C Z
            C Z
            A Z
            A Z
            A Z
            A Z
            A Z
            B X
            C Z
            C Z
            C Z
            A Z
            A Z
            A Z
            A Z
            B X
            C Z
            B X
            C Z
            A Z
            C Z
            A X
            A Y
            A Z
            C Z
            B Y
            C Z
            C Z
            B Z
            C Z
            B X
            C Z
            B X
            A Z
            A Z
            B Y
            B X
            C Z
            C Z
            C Z
            C Y
            C X
            B Y
            B Y
            C Z
            A Z
            A Z
            C Y
            C Z
            B Y
            C X
            A Z
            B X
            A Z
            C Z
            C Z
            A Z
            C X
            A Z
            B Z
            B Y
            A X
            C Z
            A Z
            B X
            A Z
            B Y
            C Z
            B X
            C Z
            B Y
            C Z
            A X
            C Z
            A Z
            C Z
            A Y
            A Y
            C Z
            C Z
            B X
            B Z
            A Z
            C Z
            A Z
            C Z
            A Y
            B X
            C Z
            A Z
            B X
            C Z
            C Z
            B Y
            C Z
            C Z
            C Y
            B Y
            B X
            C Z
            B Y
            A Z
            A Z
            B X
            B Y
            B Y
            B Y
            B Y
            B Z
            C Z
            C Z
            A Z
            C Z
            C X
            C Z
            B Z
            C X
            C X
            A Z
            A Z
            B Y
            B Z
            B Y
            C Z
            A Y
            A Z
            B Y
            B Y
            B X
            A Z
            A Z
            A Z
            C Z
            C Z
            C Z
            B Z
            A X
            A Z
            A Y
            C Z
            A Z
            A Z
            B Z
            B Y
            B Y
            A X
            C Z
            C Z
            B X
            A Z
            B Y
            A Z
            B Z
            A Z
            C Z
            C X
            A Y
            A Z
            C Z
            C Z
            C Z
            A Z
            C Z
            C Z
            B Y
            A Z
            A Z
            A Z
            A Y
            C Z
            A Z
            C Z
            B Z
            A Z
            C Z
            C X
            B Z
            C X
            B X
            C Z
            B Z
            A Y
            C Z
            C Z
            B X
            B Y
            B Y
            A Z
            B X
            A Y
            A Y
            A Z
            B Z
            C Z
            C Z
            B Z
            A Z
            C Z
            B Y
            C X
            B Z
            C Z
            B Z
            C Y
            C Z
            A Y
            A Z
            C Z
            A Z
            A Z
            C Z
            C Z
            C Z
            B Z
            A Z
            C Z
            C X
            A Z
            A Z
            B X
            B Y
            C Z
            A Y
            A Z
            C Z
            B Z
            C Z
            A Y
            A Y
            C Z
            A Z
            A Z
            B X
            A Y
            B Y
            C Z
            C Z
            B Y
            A Z
            A Y
            C X
            C Z
            C Z
            A Z
            C Z
            A Y
            C Z
            A Z
            A Z
            C Z
            A Z
            A X
            C Z
            C Z
            A Z
            B Z
            B Z
            B X
            A Z
            B X
            A Y
            A Z
            C Z
            C Z
            A Y
            B Z
            C Z
            A Z
            A Z
            C X
            B Z
            B Y
            B Y
            A Y
            B X
            B X
            C Z
            B X
            A Z
            B X
            A Z
            C Z
            C Z
            A Z
            B Y
            C Z
            C X
            C Z
            C Z
            A Z
            B X
            C Z
            C Z
            A Y
            C Z
            C Z
            B X
            B X
            B X
            A Z
            B Y
            C Z
            A Z
            C Z
            C Z
            B Y
            C Z
            A Z
            C Z
            B Y
            B Z
            C Z
            C Z
            C X
            C Z
            B Z
            C Z
            B Y
            B X
            A Z
            A Y
            B X
            A Y
            B Y
            A Z
            C Z
            C Z
            C Z
            B X
            C Z
            B X
            A Z
            B X
            B Y
            A Z
            C Z
            C Z
            C Z
            A Y
            B Y
            A Y
            C Z
            A Z
            C Z
            C Z
            A Z
            A Y
            C Z
            B X
            A Y
            A Z
            C Z
            B Y
            C Z
            A Z
            C Z
            B Y
            C Z
            C Z
            B Y
            C Z
            C Z
            B X
            C Z
            B Y
            C Z
            B Y
            A Z
            C Z
            B Y
            A Z
            C Z
            C Z
            B Y
            B X
            B Z
            A Z
            A Y
            A Z
            A Y
            C Z
            C Z
            B X
            C Z
            B Y
            C Z
            C X
            C Z
            A Y
            A Z
            C Z
            C Z
            C Z
            A Z
            B Y
            C Z
            C Z
            A Z
            B Y
            C Z
            A Y
            B Z
            B X
            A Y
            B Y
            C Z
            A Y
            C Z
            B Y
            B Y
            C Z
            C Z
            B Y
            B X
            C Z
            B X
            B Z
            B Y
            C Z
            C Z
            C Z
            A Z
            A X
            A Z
            B Z
            A Z
            C Z
            A Z
            C Z
            C Z
            A Z
            A Z
            B Z
            C Z
            C Z
            C Z
            A Z
            B Y
            A Z
            A Y
            C Z
            B X
            B X
            A Y
            C Z
            C Z
            B X
            B Z
            C X
            B X
            B Y
            A Z
            A Y
            A Z
            C Z
            B X
            C Z
            B Z
            C Z
            A Y
            C Z
            A Y
            C Z
            B Y
            B Z
            C Z
            C Z
            C Z
            C Z
            C Z
            A Z
            B Y
            C Z
            C X
            B Y
            C X
            B Y
            B Z
            B Y
            A Z
            A Z
            B X
            C Y
            A Z
            C Z
            B X
            B X
            A Z
            A Z
            B Y
            C Z
            B Y
            B Z
            A Y
            A Z
            C Z
            C Z
            B X
            A Z
            A Z
            A Z
            C Z
            C X
            C Z
            C Z
            C Z
            C Z
            A Z
            B Y
            C Z
            C Z
            C Z
            B Z
            C Z
            B X
            C Z
            A Z
            A Z
            C Z
            C Y
            B Y
            A Z
            A Y
            B Z
            A Y
            B Y
            C Z
            A Y
            C Z
            A Z
            C Z
            B X
            C Z
            A Z
            A Z
            B Z
            A Z
            B Z
            A Z
            B Y
            C Z
            B Z
            B Y
            C Z
            A Z
            A Z
            B X
            B X
            A Y
            A Z
            B Y
            A Y
            A Z
            C Z
            A X
            C Z
            A Z
            A Z
            C Z
            A Z
            B X
            A Z
            A Y
            A Y
            B Y
            A Z
            A Z
            A Z
            B Y
            B Y
            A Z
            A Z
            C Z
            C Z
            A Y
            B X
            B X
            C Z
            A Y
            C Z
            C Z
            C Z
            A Y
            C Z
            C X
            C Z
            B Y
            A Z
            B Y
            A Z
            C Z
            A Y
            C Z
            A Y
            B Z
            B X
            B Y
            B X
            B Y
            B X
            A Y
            C Z
            C Z
            B Z
            C Z
            C X
            B X
            A X
            A Z
            A Z
            B Y
            C Z
            C Z
            B Y
            C Z
            C Z
            B Y
            A Z
            B Z
            C X
            C Z
            C Z
            B Y
            C X
            C Z
            B Z
            A Z
            C Z
            B X
            A Z
            C Z
            A Z
            C Z
            B X
            B Z
            C Z
            C Z
            C Z
            A Z
            B Y
            A Y
            A Z
            C Z
            C Z
            C Z
            B Y
            A Z
            C Z
            C Z
            A Z
            B Z
            B Y
            C Z
            A Y
            A Z
            A Z
            C Z
            C Z
            C Z
            C Z
            A Z
            C Z
            C Z
            A Y
            A Y
            A Z
            C Z
            A Z
            A Z
            B X
            A Y
            A Z
            A Y
            C Z
            B Z
            A Y
            A Z
            B X
            C Z
            A Z
            A Z
            A Y
            B Y
            C Z
            C Z
            A Z
            B X
            A Y
            A Z
            C Z
            C Z
            B Y
            C Z
            A Z
            B Y
            C Z
            C Z
            B Y
            C X
            A Z
            C Z
            C Z
            C Z
            C Z
            A Z
            B Y
            A Y
            B Y
            B Z
            C Z
            A Z
            B Z
            C Z
            A X
            C Z
            C X
            A Z
            A Z
            A X
            A Z
            A Z
            A Z
            A Z
            B X
            A Z
            A Z
            A Z
            C Z
            C Z
            C Z
            C Z
            A Z
            A Y
            B X
            C Z
            B Y
            A Y
            A Z
            C Z
            C Z
            C Z
            B Y
            A Z
            B Z
            C Z
            B X
            B Z
            B Z
            B Y
            C Z
            C X
            B Y
            A Y
            C X
            C Z
            C Z
            B Y
            A Z
            C Z
            A Z
            A Z
            C Z
            C Z
            C Z
            C Z
            B Z
            C Z
            B X
            C Z
            B X
            B Z
            A Z
            B Y
            C Z
            A Z
            C Z
            A Z
            A Y
            A Z
            C Z
            B X
            C Z
            C Z
            A Z
            A Z
            C Z
            C Z
            A Z
            C Z
            A Y
            C Z
            C Z
            A Z
            A X
            A Z
            C Z
            A Z
            C Z
            C Z
            A Z
            B X
            C Z
            C Z
            C X
            A Z
            A Z
            A X
            B X
            C Z
            C Z
            A Z
            B X
            C X
            A Z
            C Z
            B Y
            C Z
            A Z
            C Z
            A Y
            A Z
            C Z
            C Z
            B X
            A Z
            B Y
            A Z
            C Z
            C X
            B Z
            C Z
            A X
            A Y
            C Z
            C Z
            C X
            B Z
            A Z
            A Z
            B Z
            A Y
            C X
            A Z
            C Z
            A Z
            C Z
            A Z
            A Z
            A Z
            C Z
            A Z
            C Z
            B X
            A Y
            A Z
            C Z
            B Y
            C Z
            A Y
            C Z
            C Z
            C Z
            C Z
            A Z
            A Z
            B Z
            C Z
            A Y
            C X
            C Z
            C Y
            B Y
            C X
            A Y
            C Z
            C Z
            B Z
            B Y
            B Z
            A Z
            B Y
            C Z
            C Z
            B X
            B Y
            B Z
            A Z
            A Z
            C Z
            B X
            A Z
            B Y
            C Z
            C Z
            B X
            C Z
            A X
            C Z
            B X
            A Y
            A Z
            B Y
            C Z
            C Z
            A Y
            A Z
            C Z
            C Z
            A Z
            C Z
            C Z
            C Z
            B X
            C Z
            B Y
            B Y
            C Z
            B Z
            C Z
            C X
            C Z
            B X
            A Z
            B Z
            B Z
            B Z
            C Z
            A X
            C Z
            B X
            A Z
            A Z
            A Z
            A Y
            C Z
            C Z
            C Z
            C X
            A Y
            A Z
            A Z
            C Z
            C Z
            A Z
            B X
            C Z
            B Y
            A X
            C X
            B Y
            B Y
            A Y
            C X
            C Z
            B X
            A Z
            A Z
            B Z
            A Y
            C Z
            C Z
            A Z
            C Z
            C Z
            A Y
            C Z
            C Z
            B Y
            C Z
            C Z
            A Z
            A Z
            B Z
            A Z
            C Z
            C Z
            C Z
            C X
            C Z
            A Z
            C Z
            C Z
            C Z
            C X
            C Z
            C Z
            A Z
            B Y
            C Z
            B X
            A Z
            C Z
            C Y
            A Z
            A Y
            A Z
            C X
            C X
            A Y
            B X
            A Y
            B Y
            B Z
            B Y
            B Y
            B Y
            B Y
            B Y
            B Y
            B Y
            B X
            B Z
            A Y
            A Y
            A Y
            B Y
            A Y
            B X
            C X
            A Z
            C Z
            A Z
            A X
            C Z
            C Z
            B Z
            C Z
            B Z
            B Z
            A Z
            A Y
            A Z
            B X
            B Z
            C Y
            A Z
            A Z
            A Z
            C Z
            C Z
            C Z
            C Z
            A Z
            C Y
            A Y
            C X
            C Z
            B Y
            C Z
            A Z
            A X
            A Z
            B Z
            C Z
            B X
            B X
            A Z
            C Z
            B X
            C Z
            C Z
            A X
            C Z
            A Z
            C Z
            C Z
            B Z
            B Y
            B X
            B Z
            A X
            A Y
            C Z
            A X
            A Y
            B Y
            A Y
            C Z
            C Z
            B X
            C Z
            B Z
            C Z
            B Y
            C Z
            A Z
            A Y
            B Z
            B Z
            A Z
            A Z
            A Z
            A Y
            C Z
            C X
            A Z
            A X
            B Y
            B X
            A Z
            C Z
            A Z
            A Z
            C Z
            B Z
            B Z
            B Y
            B Y
            A Y
            C Z
            A Z
            A Z
            C Z
            A Z
            C Z
            C Z
            B X
            B Y
            C Z
            C Z
            B X
            C X
            C Z
            A Y
            C X
            B X
            A Z
            A Z
            A Y
            B Y
            A Z
            B Z
            C Z
            C Z
            A Z
            B X
            A X
            B Y
            A Z
            B Z
            A Z
            B Y
            C Z
            A Z
            A Y
            C Z
            A Y
            C Z
            C Z
            A Z
            C Z
            C Z
            A Z
            A Y
            C Z
            A Z
            B Z
            A Y
            A Z
            C Z
            C Z
            A Y
            C Z
            A Y
            A Z
            C X
            B X
            B Z
            B Z
            B Z
            B Z
            B Y
            B X
            A Z
            C Z
            B Z
            C Z
            C Z
            C X
            A Z
            A Z
            B X
            C Z
            A Y
            C Z
            B Z
            A Z
            C X
            C Z
            C Z
            B Y
            C Z
            B Z
            A Z
            A X
            C Z
            B X
            A Z
            B Y
            C Y
            C X
            C Z
            A Z
            B Z
            A Z
            B Y
            C Z
            C Z
            A Z
            C Z
            C Z
            C Z
            C Z
            B Z
            C Z
            B X
            B Y
            A Z
            B Y
            B Y
            A Z
            C Z
            C Z
            B Y
            B Y
            B Y
            B Y
            B Z
            B X
            A Z
            B Y
            B X
            A Z
            A Y
            B X
            B X
            C Z
            C X
            B Y
            C Z
            C Z
            A Z
            C X
            C Z
            A Z
            B Y
            A Z
            A Z
            A X
            C Z
            B Y
            A Z
            C Z
            C Z
            A Z
            B Y
            B Y
            B Z
            B Z
            B X
            A X
            A Z
            A Z
            C X
            B Y
            A Y
            B Z
            A Z
            B Y
            C Z
            C Z
            B X
            C Z
            C Z
            A Z
            C Z
            A Z
            A Z
            C Z
            C Z
            C Z
            B X
            B Z
            A Y
            B X
            C Z
            A Z
            C Z
            A Y
            B Y
            A X
            C Z
            A Y
            A Z
            A Z
            A Z
            B Z
            C Z
            C Z
            C Z
            C Z
            C Z
            B Z
            B X
            C Z
            A Z
            C Z
            A X
            B Z
            C Z
            C Z
            A Z
            A Z
            B Y
            C Z
            A Z
            C Z
            B Y
            A Z
            A Y
            A Y
            C X
            C Z
            A Z
            B Y
            C Z
            C X
            C Z
            A Y
            A Z
            A Z
            B X
            C Z
            B X
            B Y
            A Y
            A Y
            B Z
            A Y
            A Z
            B Z
            A Z
            A X
            B Z
            C Z
            C X
            C Z
            C Z
            C Z
            C Z
            C X
            C Z
            A Z
            A Z
            B X
            A Z
            A Z
            A Z
            C Z
            A Z
            C Y
            B Y
            B Y
            C Z
            A Y
            B Z
            C Z
            C Z
            C Z
            A Z
            C Z
            A Z
            B Z
            B Y
            A Y
            C Z
            A Z
            A Y
            C Z
            C Z
            A Y
            B Y
            C Z
            A Z
            A Y
            A Z
            B X
            C X
            C Z
            C Z
            A Y
            A Z
            B X
            C Z
            A Z
            C Z
            C Z
            A Z
            C Z
            B X
            A Z
            A Z
            B Y
            C Z
            B X
            C Z
            C X
            A Z
            B X
            C X
            C Z
            C Z
            A Z
            B Y
            A Y
            C Z
            B Z
            B Y
            C X
            B X
            C Z
            C Y
            A Z
            A Z
            C Z
            B X
            A Z
            C Z
            B Y
            B X
            B Z
            B X
            A Y
            C Z
            C Z
            C Y
            A Z
            A Y
            C Z
            B X
            A Z
            A Z
            B Z
            B Z
            B X
            A Y
            A Z
            C Z
            A Z
            A X
            A Y
            C Z
            C Z
            B Y
            A Z
            C Z
            B Z
            A Z
            B Y
            C Z
            B Y
            A Z
            B Z
            A Z
            B Y
            B Z
            C Z
            C Z
            A Y
            C Z
            A Z
            B X
            C Z
            B X
            B X
            A Z
            C Z
            B Z
            A Z
            C Z
            C Z
            C Z
            C Z
            A Z
            C Z
            B Z
            C Z
            A Z
            B X
            C Z
            A Z
            C Z
            C Z
            A Y
            A Y
            C Z
            A Y
            A X
            C Z
            A Z
            A Z
            B Z
            A Z
            A X
            C Z
            B Y
            A Y
            B Y
            A Y
            C Z
            C Z
            B X
            A Z
            B X
            B Z
            B Z
            A Y
            C X
            A Y
            C Z
            B Y
            A Z
            A Z
            C Z
            A Z
            A Z
            B Y
            C X
            B X
            A Z
            A X
            C Z
            A Z
            B Y
            A Z
            C Z
            C Z
            A Z
            B X
            B Z
            A X
            A Y
            A Y
            B Y
            B Z
            B X
            B Z
            C X
            B Z
            C Z
            C Z
            B X
            B Y
            B X
            B Z
            B Z
            C Z
            A Z
            A X
            B X
            C Z
            A Z
            B Y
            B Y
            C X
            A Z
            B X
            A X
            C Z
            B Y
            A Y
            B Y
            A Y
            B Z
            C Z
            C Z
            C Z
            B Y
            B Y
            A Y
            C Z
            C Y
            B Z
            A Z
            C Z
            C Y
            B X
            B X
            A Z
            B Y
            A Z
            B X
            A Z
            B Y
            B Y
            C Z
            C Z
            A Z
            B Y
            C Z
            C Y
            C Z
            C Z
            A Y
            B X
            C Y
            A Y
            B X
            C Z
            C Z
            C Z
            B Z
            B Y
            A Z
            A Y
            A Z
            C Z
            C Z
            B Y
            C Z
            C Z
            A Z
            B Z
            C Z
            A Z
            A Z
            A Z
            A Y
            C X
            B Y
            B Y
            A Y
            C Z
            B Y
            B X
            B Z
            C Z
            C Z
            A Y
            A Z
            A Z
            B Z
            C Z
            C Z
            B Y
            C Z
            A Z
            C Z
            C Z
            C X
            B X
            B Y
            C Z
            A Z
            A Y
            C Z
            C Z
            C Z
            A Z
            A Y
            C Z
            A Z
            A Y
            A Y
            C Z
            B X
            C Z
            C X
            B Y
            A Z
            B Y
            C Z
            B X
            A Z
            A Y
            C Z
            A Z
            C Z
            A Z
            C Z
            C Z
            A Y
            A Z
            A Z
            B Z
            A Z
            A Z
            C Z
            A X
            A Y
            C X
            A Z
            A Z
            B Z
            B Y
            A Z
            C Z
            B Z
            C Z
            A Z
            C Z
            B X
            C Z
            B Z
            B Z
            C Z
            B Z
            A Z
            A Z
            C Z
            A Z
            C X
            C Z
            A Y
            A Z
            A X
            A Z
            B Z
            B Z
            C Z
            C X
            A Y
            C Z
            A Z
            A Z
            A X
            C Z
            C Z
            C X
            B Z
            B X
            B Z
            B Y
            C Z
            A Z
            A Y
            A Y
            B X
            A Y
            A Y
            C Z
            C Z
            B Z
            A Z
            B Z
            C Z
            A Z
            B Y
            B Y
            C Z
            A Z
            C Z
            A Z
            B Y
            A Z
            C Z
            B X
            C Z
            A Z
            C Z
            A Y
            B Y
            A Y
            B Z
            A Y
            C Z
            A Z
            C Z
            B X
            B X
            B Y
            B X
            C Z
            A X
            B Y
            B Z
            C Z
            A Y
            C Z
            B Z
            C Z
            A Z
            C X
            C Z
            A Z
            A Y
            C Z
            C Z
            B Y
            C Z
            B Y
            C Z
            C Z
            B Z
            A Z
            C Z
            B Y
            B X
            A Z
            C Z
            C Z
            A Z
            C Z
            C Z
            B Y
            A Z
            B X
            C Z
            B Y
            B X
            A Z
            C Z
            A Z
            C Z
            A Z
            C Z
            B Y
            C Z
            A Z
            B X
            C Z
            A Y
            A Y
            A Z
            A Y
            A Z
            A X
            C Z
            B X
            B Z
            C Z
            A Z
            C X
            A Z
            A Z
            A Z
            C Z
            A Z
            C Z""";
}
